[package]
name = 'auction'
version = '1.0.0'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'e1c6a5713301ed72bf3a846ab9536d002ac801d6'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies.AptosToken]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'e1c6a5713301ed72bf3a846ab9536d002ac801d6'
subdir = 'aptos-move/framework/aptos-token'


[addresses]
auction="0xe2e4a10fb4b9fbf8b896b619d8a9d8d305243782c2d0e030d97f622ee5127bd3"